package com.bank.customer.infrastructure.persistence.mapper;

import com.bank.customer.domain.model.Address;
import com.bank.customer.domain.model.Customer;
import com.bank.customer.domain.model.CustomerId;
import com.bank.customer.domain.model.Gender;
import com.bank.customer.domain.model.HashedPassword;
import com.bank.customer.domain.model.Identification;
import com.bank.customer.domain.model.PersonName;
import com.bank.customer.domain.model.PersonalData;
import com.bank.customer.domain.model.PhoneNumber;
import com.bank.customer.infrastructure.persistence.entity.CustomerEntity;
import org.springframework.stereotype.Component;

/**
 * Translates between the domain model and the persistence model.
 *
 * <p>This class is the price of keeping the two models separate, and it is
 * worth paying. Without it, a column rename would ripple into the business
 * rules, JPA's requirements (no-args constructor, mutable fields, no final
 * state) would dictate the shape of the aggregate, and the domain would inherit
 * an inheritance strategy chosen for the benefit of a query planner.
 *
 * <p>Written by hand rather than generated by MapStruct. At this size the
 * generated code would be no shorter, and hand-writing it makes the one
 * asymmetry below impossible to miss.
 */
@Component
public class CustomerEntityMapper {

    /**
     * Domain to persistence.
     *
     * <p>{@code version} is deliberately not copied. It belongs to Hibernate:
     * the entity carries it, the aggregate has never heard of it, and that is
     * correct — optimistic locking is a persistence strategy, not a business
     * rule. Copying it here would leak the mechanism into the model and, worse,
     * would let a stale value overwrite the one Hibernate is tracking.
     */
    public CustomerEntity toEntity(Customer customer) {
        CustomerEntity entity = new CustomerEntity();
        applyTo(entity, customer);
        entity.setId(customer.id().value());
        entity.setCreatedAt(customer.createdAt());
        return entity;
    }

    /** Copies the mutable state onto an entity Hibernate is already managing. */
    public void applyTo(CustomerEntity entity, Customer customer) {
        entity.setName(customer.name().value());
        entity.setGender(CustomerEntity.GenderCode.valueOf(customer.gender().name()));
        entity.setIdentification(customer.identification().value());
        entity.setAddress(customer.address().value());
        entity.setPhone(customer.phone().value());
        entity.setPasswordHash(customer.password().value());
        entity.setActive(customer.isActive());
        entity.setUpdatedAt(customer.updatedAt());
    }

    /**
     * Persistence to domain.
     *
     * <p>Uses {@code rehydrate}, never {@code register}. Loading a row is not a
     * business fact, and {@code register} would raise a
     * {@code CustomerRegistered} event for a customer that was created months
     * ago — which the outbox would dutifully publish, and every read model
     * downstream would dutifully believe.
     */
    public Customer toDomain(CustomerEntity entity) {
        PersonalData profile = new PersonalData(
                new PersonName(entity.getName()),
                Gender.valueOf(entity.getGender().name()),
                new Identification(entity.getIdentification()),
                new Address(entity.getAddress()),
                new PhoneNumber(entity.getPhone()));

        return Customer.rehydrate(
                new CustomerId(entity.getId()),
                profile,
                new HashedPassword(entity.getPasswordHash()),
                entity.isActive(),
                entity.getCreatedAt(),
                entity.getUpdatedAt());
    }
}
